### ISSUE TITLE
Add Lint Checker that Checks for `Log.`Recommends Timber Instead

### ISSUE THREAD

**Issue by octohub** [Rightpoint/android-template#25]

**Comment by jkim24** [comment]
Here's a [list](https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks) of sample `detectors` from Google. `Detectors` do the heavy lifting in lint checks and you should be able to find a sample that does what we're looking for.

**Comment by k-thryn** [comment]
Because Timber includes a [Log lint check](https://github.com/JakeWharton/timber#lint), and template projects are generated with Timber pre-configured, we've decided not to reinvent the wheel! Closing this issue. Some other custom lint checks might be a nice an enhancement down the road, suggestions are welcome.
